#!/usr/bin/env python3
"""Fetch + wrap Arduino libraries for the IDF-as-build flow.

Reads arduino_libraries.json, shallow-clones each entry into
arduino_libraries/<name>/, injects a generic CMakeLists.txt if the lib
doesn't already ship one, and applies any in-tree patches that the
Arduino lib needs to compile against IDF v5.5 + Arduino-ESP32 v3.x.

The patch logic is ported from scripts/pre_script.py so the IDF flow
doesn't depend on PlatformIO being installed. Each patch is
idempotent via a sentinel marker.

Run from idf-build/:

    python3 fetch_arduino_libs.py

Re-run is safe: existing lib dirs are left alone and patches skip
themselves if already applied. Pass --force to wipe and re-fetch.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONFIG_PATH = HERE / "arduino_libraries.json"
TARGET_DIR = HERE / "arduino_libraries"


# Generic CMakeLists template injected for libs that ship none. Uses
# CONFIGURE_DEPENDS so adding/removing source files re-triggers a
# CMake reconfigure. PRIV_REQUIRES on arduino-esp32 because virtually
# every Arduino lib pulls Arduino.h / Wire.h / SPI.h / WiFi.h, all of
# which come from the core. mbedtls + esp_http_client are listed for
# libs (e.g. WebSockets, Nostrduino) that reach into TLS directly.
CMAKE_TEMPLATE = """\
# Auto-generated by fetch_arduino_libs.py. Do not edit; rerun the
# fetcher with --force if the layout of the upstream lib changes.
#
# CONFIGURE_DEPENDS is intentionally NOT used: IDF's component-scan
# pass runs CMakeLists.txt in script mode, where that glob option is
# illegal. Re-run idf.py reconfigure if you add/remove source files.
#
# Non-recursive at the root (so a top-level Foo.cpp gets picked up
# but test/unit_test.cpp / examples/Foo.ino does not) plus a
# recursive sweep under src/ (Arduino-library standard layout).

file(GLOB _root_srcs
    "${CMAKE_CURRENT_LIST_DIR}/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)
file(GLOB_RECURSE _src_tree_srcs
    "${CMAKE_CURRENT_LIST_DIR}/src/*.c"
    "${CMAKE_CURRENT_LIST_DIR}/src/*.cpp"
)
set(_srcs ${_root_srcs} ${_src_tree_srcs})

# Belt-and-braces: drop anything that still looks like test or example
# code in case a lib keeps its sources under src/test/ etc.
list(FILTER _srcs EXCLUDE REGEX "/(test|tests|examples?)/")

set(_inc_dirs ".")
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/src")
    list(APPEND _inc_dirs "src")
endif()

idf_component_register(
    SRCS ${_srcs}
    INCLUDE_DIRS ${_inc_dirs}
    REQUIRES espressif__arduino-esp32 mbedtls esp_http_client
)
"""


# ---------- patches ----------------------------------------------------------

def patch_ubitcoin_esp_random(lib_dir: Path) -> bool:
    """Add <esp_random.h> include to uBitcoin's trezor/rand.c.

    IDF v5.x moved esp_random() out of <esp_system.h>; uBitcoin still
    only includes the latter. Globbed because uBitcoin appears at the
    lib root in standalone, but nested under Nostrduino/src/uBitcoin/
    when Nostrduino vendors it.
    """
    sentinel = "/* patched by fetch_arduino_libs.py for IDF v5 esp_random move */"
    targets = list(lib_dir.glob("**/trezor/rand.c"))
    changed = False
    for path in targets:
        src = path.read_text()
        if sentinel in src:
            continue
        new = src.replace(
            "  #include <esp_system.h>",
            f"{sentinel}\n  #include <esp_system.h>\n  #include <esp_random.h>",
            1,
        )
        if new == src:
            continue
        path.write_text(new)
        changed = True
    return changed


def patch_gxepd2_pointer_compare(lib_dir: Path) -> bool:
    """Replace ordered pointer-vs-int checks in GxEPD2 with != nullptr.

    The dsbaars/GxEPD2#universal_pin fork swapped int pin members for
    UniversalPin* but left `if (_rst >= 0)` style checks intact. GCC
    11+ rejects those as errors.
    """
    sentinel = "// patched by fetch_arduino_libs.py: GxEPD2 fork pin>=0 -> != nullptr"
    pin_re = re.compile(r"\bif \((_(rst|dc|cs|busy))\s*>=\s*0\)")
    changed = False
    for path in lib_dir.rglob("*"):
        if path.suffix not in (".cpp", ".h"):
            continue
        src = path.read_text()
        if sentinel in src:
            continue
        new = pin_re.sub(r"if (\1 != nullptr)", src)
        if new == src:
            continue
        new = f"{sentinel}\n{new}"
        path.write_text(new)
        changed = True
    return changed


def patch_gxepd2_stdexcept(lib_dir: Path) -> bool:
    """Inject <stdexcept> into GxEPD2_EPD.cpp.

    std::runtime_error is referenced at ~line 163 but never included;
    older libstdc++ pulled it transitively.
    """
    path = lib_dir / "src" / "GxEPD2_EPD.cpp"
    if not path.exists():
        return False
    src = path.read_text()
    if "<stdexcept>" in src:
        return False
    new = src.replace(
        '#include "GxEPD2_EPD.h"',
        '#include "GxEPD2_EPD.h"\n#include <stdexcept>',
        1,
    )
    if new == src:
        return False
    path.write_text(new)
    return True


def patch_websockets_max_data_size(lib_dir: Path) -> bool:
    """Make WEBSOCKETS_MAX_DATA_SIZE overridable via a -D flag.

    The Links2004 lib hard-codes 15 KB; mempool.space's initial
    history burst is ~18 KB and gets rejected with close code 1009.
    """
    header = lib_dir / "src" / "WebSockets.h"
    if not header.exists():
        return False
    sentinel = "// patched by fetch_arduino_libs.py to allow build-flag override"
    src = header.read_text()
    if sentinel in src:
        return False
    new = src.replace(
        "#define WEBSOCKETS_MAX_DATA_SIZE (15 * 1024)",
        f"{sentinel}\n#ifndef WEBSOCKETS_MAX_DATA_SIZE\n"
        "#define WEBSOCKETS_MAX_DATA_SIZE (15 * 1024)\n#endif",
    )
    if new == src:
        return False
    header.write_text(new)
    return True


def patch_websockets_rx_internal_dram(lib_dir: Path) -> bool:
    """Force the Links2004 WebSockets RX frame buffer into internal DRAM.

    Mirrors the PIO-side patch: the default malloc may hand out PSRAM
    for large frames, which trips the TLS/Wi-Fi RX path.
    """
    cpp = lib_dir / "src" / "WebSockets.cpp"
    if not cpp.exists():
        return False
    sentinel = "// patched by fetch_arduino_libs.py to force RX buffer to internal DRAM"
    src = cpp.read_text()
    if sentinel in src:
        return False
    target = "payload = (uint8_t *)malloc(header->payloadLen + 1);"
    replacement = (
        f"{sentinel}\n"
        "#if defined(ESP32) && __has_include(<esp_heap_caps.h>)\n"
        "        payload = (uint8_t *)heap_caps_malloc(header->payloadLen + 1, MALLOC_CAP_INTERNAL);\n"
        "        if (!payload) {\n"
        "            payload = (uint8_t *)heap_caps_malloc(header->payloadLen + 1, MALLOC_CAP_DEFAULT);\n"
        "        }\n"
        "#else\n"
        "        payload = (uint8_t *)malloc(header->payloadLen + 1);\n"
        "#endif"
    )
    new = src.replace(target, replacement)
    if new == src:
        return False
    if "#include <esp_heap_caps.h>" not in new:
        new = new.replace(
            '#include "WebSockets.h"',
            '#include "WebSockets.h"\n'
            "#if defined(ESP32) && __has_include(<esp_heap_caps.h>)\n"
            "#include <esp_heap_caps.h>\n#endif",
            1,
        )
    cpp.write_text(new)
    return True


PATCH_FNS = {
    "ubitcoin_esp_random": patch_ubitcoin_esp_random,
    "gxepd2_pointer_compare": patch_gxepd2_pointer_compare,
    "gxepd2_stdexcept": patch_gxepd2_stdexcept,
    "websockets_max_data_size": patch_websockets_max_data_size,
    "websockets_rx_internal_dram": patch_websockets_rx_internal_dram,
}


# ---------- fetch ------------------------------------------------------------

def fetch(name: str, git: str, ref: str, force: bool) -> Path:
    dst = TARGET_DIR / name
    if dst.exists():
        if force:
            shutil.rmtree(dst)
        else:
            print(f"[skip ] {name} (already present at {dst.relative_to(HERE)})")
            return dst

    TARGET_DIR.mkdir(exist_ok=True)
    print(f"[fetch] {name} <- {git} @ {ref}")

    # Try shallow clone with --branch first (works for both tags and
    # branch names but only one ref). If that fails (rare on forks
    # where the ref isn't reachable from a shallow tip), fall back to
    # a full clone + checkout.
    rc = subprocess.run(
        ["git", "clone", "--depth", "1", "--branch", ref, git, str(dst)],
        stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
    )
    if rc.returncode != 0:
        if dst.exists():
            shutil.rmtree(dst)
        print(f"        shallow clone failed, retrying full clone")
        subprocess.run(["git", "clone", git, str(dst)], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        subprocess.run(["git", "-C", str(dst), "checkout", ref], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

    # Strip .git so the vendored tree doesn't show up as a submodule.
    shutil.rmtree(dst / ".git", ignore_errors=True)
    return dst


def ensure_cmakelists(lib_dir: Path, extra_requires: list[str] | None = None) -> None:
    cmake = lib_dir / "CMakeLists.txt"
    if cmake.exists():
        # Upstream Arduino-as-IDF-component libs often write
        # `REQUIRES arduino` (the short alias used by PIO's dual-
        # framework setup). IDF Component Manager publishes the core
        # under its namespaced name `espressif__arduino-esp32`; the
        # short alias is not registered in this build, so rewrite it.
        # Sentinel-guarded to stay idempotent.
        sentinel = "# patched by fetch_arduino_libs.py: arduino -> espressif__arduino-esp32"
        src = cmake.read_text()
        if sentinel not in src:
            new = re.sub(
                r"\b(arduino)\b(?=[\s\n)\\]*(?:#.*)?$)",
                "espressif__arduino-esp32",
                src,
                flags=re.MULTILINE,
            )
            # Simpler/safer pass: any standalone "arduino" word inside
            # a REQUIRES/PRIV_REQUIRES line.
            new_lines = []
            for line in src.splitlines():
                stripped = line.strip()
                if (stripped.startswith(("REQUIRES", "PRIV_REQUIRES"))
                        or "REQUIRES " in line or "PRIV_REQUIRES " in line):
                    line = re.sub(r"\barduino\b", "espressif__arduino-esp32", line)
                new_lines.append(line)
            new = "\n".join(new_lines)
            if new != src:
                cmake.write_text(f"{sentinel}\n{new}")
                print(f"        patched CMakeLists.txt: arduino -> espressif__arduino-esp32")
        return
    template = CMAKE_TEMPLATE
    if extra_requires:
        # Splice extra deps onto the REQUIRES line so the auto-template
        # can express inter-Arduino-lib relationships (e.g. universal_pin
        # depends on MCP23017, GxEPD2 on Adafruit_GFX_Library, etc.)
        extra = " ".join(extra_requires)
        template = template.replace(
            "REQUIRES espressif__arduino-esp32 mbedtls esp_http_client",
            f"REQUIRES espressif__arduino-esp32 mbedtls esp_http_client {extra}",
            1,
        )
    cmake.write_text(template)
    print(f"        injected CMakeLists.txt template"
          + (f" (+ extra requires: {' '.join(extra_requires)})" if extra_requires else ""))


def apply_patches(name: str, lib_dir: Path, patches: list[str]) -> None:
    for patch_name in patches:
        fn = PATCH_FNS.get(patch_name)
        if fn is None:
            print(f"        WARNING: unknown patch '{patch_name}' for {name}")
            continue
        if fn(lib_dir):
            print(f"        applied patch: {patch_name}")
        else:
            print(f"        patch already present or no-op: {patch_name}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true",
                        help="wipe and re-fetch every lib")
    args = parser.parse_args(argv)

    cfg = json.loads(CONFIG_PATH.read_text())
    for lib in cfg["libraries"]:
        # Allow inline {"_comment": "..."} entries to document why a
        # given lib was moved out of the vendoring list.
        if "name" not in lib:
            continue
        name = lib["name"]
        try:
            lib_dir = fetch(name, lib["git"], lib["ref"], args.force)
        except subprocess.CalledProcessError as exc:
            print(f"        ERROR fetching {name}: {exc}", file=sys.stderr)
            return 1
        ensure_cmakelists(lib_dir, lib.get("extra_requires"))
        apply_patches(name, lib_dir, lib.get("patches", []))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
